#!/usr/bin/env python

import random 
    
def main():
 """Start a guessing genre music."""
 print("Guess the genre music!")
 
 music = ["Classical","Hip hop","rock","Disco","Alternative","metal"]
     
 x = random.choice(music)
 guess = None
     
 while x != guess:
         
    guess = str(input("Pick a genre music:"))
         
    if str("disco") == guess:
        print("correct.!")
        break
    else:
        print("Try again.")
main()
